### ISSUE TITLE
Error connect

### ISSUE THREAD

**Issue by AILLPTELTD** [chrisgitrepo/fix-client#1]
![image](https://user-images.githubusercontent.com/56570494/69416560-79797c80-0d49-11ea-99a7-cdd1a2e11c3f.png)
affter connect, i send logon=> throw error
Can you help me?

**Comment by chrisgitrepo** [comment]
This a network error. It doesnt have access to the internet or you have a firewall or proxy blocking TCP requests.

**Comment by chrisgitrepo** [comment]
Issue stale, closing
